--To check all columns
SELECT
*
FROM
AUDIENCE.RATINGS.BRIGHTTVUPROFILES
--To check all columns
SELECT
*
FROM
AUDIENCE.RATINGS.BRIGHTTV_VIEWERSHIP2
  --Renaming columns to avoid duplicate column
SELECT
B.USERID AS CustomerID,
FROM AUDIENCE.RATINGS.BRIGHTTV_VIEWERSHIP2 AS B; 

--Conducted a Left Outer join on UserID 

    SELECT *
    FROM AUDIENCE.RATINGS.BRIGHTTVUPROFILES AS A
    INNER JOIN AUDIENCE.RATINGS.BRIGHTTV_VIEWERSHIP2 AS B ON
     A.USERID = B.USERID;
    
    
     --Renaming columns to avoid duplicate column
 --Renaming columns to avoid duplicate column
SELECT
B.USERID AS CustomerID,
FROM AUDIENCE.RATINGS.BRIGHTTV_VIEWERSHIP2 AS B;
   
-- Checking for missing values - used the inner join syntax as new table --
  SELECT
  A.USERID AS ProfileUserID,
  B.USERID AS CustomerID,
  A.NAME,
  A.SURNAME,
  A.EMAIL,
  A.GENDER,
  A.RACE,
  A.AGE,
  A.PROVINCE,
  A.SOCIAL_MEDIA_HANDLE,
  B.CHANNEL2,
  B.DURATION2,
  B.RECORDDATE2
FROM AUDIENCE.RATINGS.BRIGHTTVUPROFILES AS A
INNER JOIN AUDIENCE.RATINGS.BRIGHTTV_VIEWERSHIP2 AS B
  ON A.USERID = B.USERID
WHERE A.USERID IS NULL 
   OR A.NAME IS NULL 
   OR A.SURNAME IS NULL 
   OR A.EMAIL IS NULL 
   OR A.GENDER IS NULL 
   OR A.RACE IS NULL 
   OR A.AGE IS NULL 
   OR A.PROVINCE IS NULL 
   OR A.SOCIAL_MEDIA_HANDLE IS NULL
   OR B.CHANNEL2 IS NULL 
   OR B.DURATION2 IS NULL
   OR B.RECORDDATE2 IS NULL;
--Replacing missing records with Zero

SELECT
  IFNULL(A.USERID, 'UNKNOWN') AS ProfileUserID,
  IFNULL(B.USERID, 'UNKNOWN') AS CustomerID,
  IFNULL(A.NAME,'UNKNOWN') AS NAME,
  IFNULL(A.SURNAME, 'UNKNOWN') AS SURNAME,
  IFNULL(A.EMAIL, 'UNKNOWN') AS EMAIL,
  IFNULL(A.GENDER, 'UNKNOWN') AS GENDER,
  IFNULL(A.RACE, 'UNKNOWN') AS RACE,
  IFNULL(A.AGE, 'UNKNOWN') AS AGE,
  IFNULL(A.PROVINCE, 'UNKNOWN') AS PROVINCE,
  IFNULL(A.SOCIAL_MEDIA_HANDLE, 'UNKNOWN') AS SOCIAL_MEDIA_HANDLE,
  IFNULL(B.CHANNEL2, 'UNKNOWN') AS CHANNEL2,
  IFNULL(B.DURATION2, 'UNKNOWN') AS DURATION2,
  IFNULL(B.RECORDDATE2, 'UNKNOWN') AS RECORDDATE2
FROM AUDIENCE.RATINGS.BRIGHTTVUPROFILES AS A
INNER JOIN AUDIENCE.RATINGS.BRIGHTTV_VIEWERSHIP2 AS B
  ON A.USERID = B.USERID;

--General data checks
SELECT
MIN(AGE)AS MIN_AGE 
FROM AUDIENCE.RATINGS.BRIGHTTVUPROFILES AS A
INNER JOIN AUDIENCE.RATINGS.BRIGHTTV_VIEWERSHIP2 AS B
  ON A.USERID = B.USERID;
SELECT
MAX(AGE)AS MAX_AGE 
FROM AUDIENCE.RATINGS.BRIGHTTVUPROFILES AS A
INNER JOIN AUDIENCE.RATINGS.BRIGHTTV_VIEWERSHIP2 AS B
  ON A.USERID = B.USERID;
  
SELECT 'Gender' AS Category, GENDER AS Value, COUNT(*) AS Count
FROM AUDIENCE.RATINGS.BRIGHTTVUPROFILES
WHERE GENDER IS NOT NULL
GROUP BY GENDER

UNION ALL

-- Province Count
SELECT 'Province' AS Category, PROVINCE AS Value, COUNT(*) AS Count
FROM AUDIENCE.RATINGS.BRIGHTTVUPROFILES
WHERE PROVINCE IS NOT NULL
GROUP BY PROVINCE

UNION ALL

-- Race Count
SELECT 'Race' AS Category, RACE AS Value, COUNT(*) AS Count
FROM AUDIENCE.RATINGS.BRIGHTTVUPROFILES
WHERE RACE IS NOT NULL
GROUP BY RACE;

 -- Last Code
 SELECT
  A.USERID,
  A.NAME,
  A.SURNAME,
  A.EMAIL,
  A.GENDER,
  A.RACE,
  A.AGE,
  A.PROVINCE,
  A.SOCIAL_MEDIA_HANDLE,
  B.CHANNEL2,
  B.DURATION2,
  B.RECORDDATE2,

  -- Age Group Classification
  CASE 
    WHEN A.AGE BETWEEN 0 AND 17 THEN 'CHILD'
    WHEN A.AGE BETWEEN 18 AND 35 THEN 'YOUTH'
    WHEN A.AGE BETWEEN 36 AND 60 THEN 'ADULT'
    WHEN A.AGE > 60 THEN 'PENSIONER'
    ELSE 'NOT SPECIFIED'
  END AS AGE_GROUP,

  -- Viewing Duration Classification
  CASE 
    WHEN B.DURATION2 BETWEEN '00:00:00' AND '02:59:59' THEN '0-3 HOURS WATCH'
    WHEN B.DURATION2 BETWEEN '03:00:00' AND '05:59:59' THEN '3-6 HOURS WATCH'
    WHEN B.DURATION2 BETWEEN '06:00:00' AND '08:59:59' THEN '6-9 HOURS WATCH'
    ELSE '9-12 HOURS WATCH'
  END AS WATCHING_DURATION,

  -- Convert string to timestamp
  TO_TIMESTAMP(B.RECORDDATE2, 'YYYY/MM/DD HH24:MI') AS RECORD_TIMESTAMP,

  -- Date Components
  EXTRACT(YEAR FROM TO_TIMESTAMP(B.RECORDDATE2, 'YYYY/MM/DD HH24:MI')) AS RECORD_YEAR,
  TO_CHAR(TO_TIMESTAMP(B.RECORDDATE2, 'YYYY/MM/DD HH24:MI'), 'Month') AS RECORD_MONTH_NAME,
  EXTRACT(DAY FROM TO_TIMESTAMP(B.RECORDDATE2, 'YYYY/MM/DD HH24:MI')) AS RECORD_DAY_OF_MONTH,
  TO_CHAR(TO_TIMESTAMP(B.RECORDDATE2, 'YYYY/MM/DD HH24:MI'), 'Day') AS RECORD_DAY_NAME,
  EXTRACT(HOUR FROM TO_TIMESTAMP(B.RECORDDATE2, 'YYYY/MM/DD HH24:MI')) AS RECORD_HOUR,
  EXTRACT(MINUTE FROM TO_TIMESTAMP(B.RECORDDATE2, 'YYYY/MM/DD HH24:MI')) AS RECORD_MINUTES,

  -- Weekday/Weekend Classification
 CASE
  WHEN DAYOFWEEK(TO_TIMESTAMP(B.RECORDDATE2, 'YYYY/MM/DD HH24:MI')) IN (1, 7) THEN 'WEEKEND'
  ELSE 'WEEKDAY'
END AS DAY_OF_WEEK_CLASSIFICATION,

  -- Time of Day Classification
  CASE 
    WHEN EXTRACT(HOUR FROM TO_TIMESTAMP(B.RECORDDATE2, 'YYYY/MM/DD HH24:MI')) BETWEEN 6 AND 11 THEN 'MORNING'
    WHEN EXTRACT(HOUR FROM TO_TIMESTAMP(B.RECORDDATE2, 'YYYY/MM/DD HH24:MI')) BETWEEN 12 AND 17 THEN 'AFTERNOON'
    WHEN EXTRACT(HOUR FROM TO_TIMESTAMP(B.RECORDDATE2, 'YYYY/MM/DD HH24:MI')) BETWEEN 18 AND 23 THEN 'EVENING'
    ELSE 'NIGHT'
  END AS TIME_OF_DAY

FROM AUDIENCE.RATINGS.BRIGHTTVUPROFILES AS A
INNER JOIN AUDIENCE.RATINGS.BRIGHTTV_VIEWERSHIP2 AS B
  ON A.USERID = B.USERID;
